/*
-----------------------------------------------------------------------------
Filename:    GASRendering.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for VC10 (July 2011)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/
#ifndef __GASRendering_h_
#define __GASRendering_h_

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif

#include "GameAudioWrapper.h"
#include "GameAudioObject.h"
class GASRendering : public BaseApplication
{
public:
    GASRendering(void);
    virtual ~GASRendering(void);

protected:
    virtual void createScene(void);
	void CreateGui();
	// OIS::KeyListener
    virtual bool keyPressed( const OIS::KeyEvent &arg );
    virtual bool keyReleased( const OIS::KeyEvent &arg );

	 // Ogre::FrameListener
    virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt);


	virtual void buttonHit(OgreBites::Button* button);
	virtual void sliderMoved(OgreBites::Slider* slider);
	virtual void checkBoxToggled(OgreBites::CheckBox* box);

	//------------SOUND
//	GAS::GameAudioWrapper mAudioWrapper;
	Ogre::AnimationState *mSinbadAnimation;
	Ogre::SceneNode* mSpeaker1Node;
	Ogre::SceneNode* mSpeaker2Node;
	GAS::GameAudioObject *mSpeaker1;
	GAS::GameAudioObject *mSpeaker2;

	bool mSpeak1MovingLeft;
	bool mSpeak1MovingRight;
	bool mSpeak1MovingFwd;
	bool mSpeak1MovingBack;

	OgreBites::Label* mSpeaker1Label;	
	OgreBites::Button*		mSpeaker1PlayButton;
	OgreBites::Button*		mSpeaker1PauseButton;
	OgreBites::Button*		mSpeaker1StopButton;
	OgreBites::Slider* mSpeaker1PitchSlider;
	OgreBites::Slider* mSpeaker1GainSlider;
	OgreBites::CheckBox *mSpeaker1LoopCheckbox;
	OgreBites::Slider *mSpeaker1RolloffSlider;
	OgreBites::Slider *mSpeaker1ReferenceDistanceSlider;

	OgreBites::Label* mSpeaker2Label;	
	OgreBites::Button*		mSpeaker2PlayButton;
	OgreBites::Button*		mSpeaker2PauseButton;
	OgreBites::Button*		mSpeaker2StopButton;
	OgreBites::Slider* mSpeaker2PitchSlider;
	OgreBites::Slider* mSpeaker2GainSlider;
	OgreBites::CheckBox *mSpeaker2LoopCheckbox;
	OgreBites::Slider *mSpeaker2RolloffSlider;
	OgreBites::Slider *mSpeaker2ReferenceDistanceSlider;

};

#endif // #ifndef __GASRendering_h_
