/*
-----------------------------------------------------------------------------
Filename:    GASRendering.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for VC10 (July 2011)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/
#ifndef __GASRendering_h_
#define __GASRendering_h_

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif

#include "GameAudioWrapper.h"
#include "GameAudioObject.h"
class GASRendering : public BaseApplication
{
public:
    GASRendering(void);
    virtual ~GASRendering(void);

protected:
    virtual void createScene(void);
	// OIS::KeyListener
    virtual bool keyPressed( const OIS::KeyEvent &arg );
    virtual bool keyReleased( const OIS::KeyEvent &arg );

	 // Ogre::FrameListener
    virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt);

	//------------SOUND
//	GAS::GameAudioWrapper mAudioWrapper;
	Ogre::SceneNode* mSpeaker1Node;
	GAS::GameAudioObject *mSpeaker1;
	GAS::GameAudioObject *mSpeaker2;

	bool mSpeak1MovingLeft;
	bool mSpeak1MovingRight;
	bool mSpeak1MovingFwd;
	bool mSpeak1MovingBack;
};

#endif // #ifndef __GASRendering_h_
